"""BPE-like coarsening of labeled directed trees represented as NetworkX graphs."""

from .canonical import attachment_slice, external_root_positions, root_count, site_count
from .coarsener import TreeCoarsener
from .compose import combine
from .decoder import LazyTreeDecoder, StagedTreeDecoder, TreeDecoder
from .stage_decoder import StructuralStageDecoder
from .encoder import EncodingRule, LazyTreeEncoder, TreeEncoder
from .exceptions import NotFittedError, TreeCoarseningError, ValidationError
from .schema import (
    GraphInput,
    as_graph_list,
    encoded_node_attrs,
    max_component_time,
    normalize_coarsenable_tree,
)
from .structural import CompositeType
from .provenance import (
    NODE_ATTRS_KEY,
    PROVENANCE_KEY,
    normalize_super_uids,
    split_super_uids,
    validate_super_uids,
)
from .coarseners import (
    EdgeBPECoarsener,
    EdgeBPEEncoder,
    EdgeBPERule,
    EdgeBPEWithAutoStarCoarsener,
    EdgeBPEWithAutoStarEncoder,
    EdgeStarRule,
    GreedyStarBPECoarsener,
    GreedyStarBPEEncoder,
    NamedVertexCoarsener,
    NamedVertexEncoder,
    StarCoarsener,
    StarEncoder,
    StarRule,
    edge_bpe_token,
    edge_star_token,
    named_component_token,
    star_token,
)
from .utils import (
    add_starbursts,
    make_edge_bpe_dataset,
    make_named_component_tree,
    make_repeated_edge_tree,
    make_starburst_dataset,
    random_galton_watson_tree,
)
from .validation import validate_coarsenable_tree
from .vocabulary import (
    BASE_NAMESPACE,
    Token,
    TokenSpec,
    VocabEntry,
    Vocabulary,
    base_token,
    format_token,
    is_base_token,
    normalize_attach_map,
    raw_label_from_base_token,
)

__all__ = [
    "BASE_NAMESPACE",
    "validate_coarsenable_tree",
    "normalize_coarsenable_tree",
    "max_component_time",
    "encoded_node_attrs",
    "as_graph_list",
    "GraphInput",
    "NODE_ATTRS_KEY",
    "PROVENANCE_KEY",
    "EdgeBPECoarsener",
    "EdgeBPEEncoder",
    "EdgeBPERule",
    "EdgeBPEWithAutoStarCoarsener",
    "EdgeBPEWithAutoStarEncoder",
    "EdgeStarRule",
    "EncodingRule",
    "GreedyStarBPECoarsener",
    "GreedyStarBPEEncoder",
    "LazyTreeDecoder",
    "LazyTreeEncoder",
    "NamedVertexCoarsener",
    "NamedVertexEncoder",
    "NotFittedError",
    "StagedTreeDecoder",
    "StructuralStageDecoder",
    "StarCoarsener",
    "StarEncoder",
    "StarRule",
    "Token",
    "TokenSpec",
    "CompositeType",
    "TreeCoarsener",
    "TreeCoarseningError",
    "TreeDecoder",
    "TreeEncoder",
    "ValidationError",
    "VocabEntry",
    "Vocabulary",
    "add_starbursts",
    "attachment_slice",
    "base_token",
    "combine",
    "edge_bpe_token",
    "edge_star_token",
    "named_component_token",
    "external_root_positions",
    "format_token",
    "is_base_token",
    "make_edge_bpe_dataset",
    "make_named_component_tree",
    "make_repeated_edge_tree",
    "make_starburst_dataset",
    "normalize_attach_map",
    "normalize_super_uids",
    "random_galton_watson_tree",
    "raw_label_from_base_token",
    "root_count",
    "site_count",
    "split_super_uids",
    "star_token",
    "validate_super_uids",
]
